title: "Thomas Duncan Richu"
email: "chiradans@gmail.com"
description: "Portfolio of Thomas Duncan Richu, showcasing skills, education, community service, and projects."
baseurl: "" # Base URL for the site
url: "https://Tommzzy.github.io" # URL for GitHub Pages
theme: minima
